### ISSUE TITLE
configure localhost

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/asbel-esteve#2]
Do I have to configure the localhost in this way?
![image](https://cloud.githubusercontent.com/assets/12971681/12026583/a87aa816-adbb-11e5-95ca-94c1e4fe54e8.png)
And do I write in DocumentRoot: Users/anton/Desenvolupament/Asble-Estebe, and in ServerName: asbelestebe.dev  ?
I thought to find the pas a repas configuration in this file...

**Comment by aserratorta** [comment]
I tried to render the homepage follow tis steps:
https://medium.com/@danilosapad/how-to-set-up-virtual-hosts-on-mac-os-x-10-10-yosemite-afac19e982cf#.jdif40o6n
And, as a result, it shows me this:
![image](https://cloud.githubusercontent.com/assets/12971681/12081968/eda2df26-b289-11e5-9429-24a4ca952b18.png)

**Comment by davidromani** [comment]
It's better to follow the same config pattern as in the other project (pas-a-repas)
